### ISSUE TITLE
Bundle php language server with theia-php-extension

### ISSUE THREAD

**Issue by meysholdt** [theia-ide/theia-php-extension#10]
right now, the language server is being installed in a `postinstall` script. This is annoying for Theia developers, because 
* it requires them to have `php` and `composer` installed when running `yarn install` on Theia even though they don't work with php. This assumes "Theia" has a dependency to `theia-php-extenion`.
* running `composer install` during `yarn install` unnecessarily slows down `yarn install`.

The proposed solution is to bundle the php language server and it's dependencies as part of the theia-php-extension. This assumes `composer install` produces platform-independent results (to be confirmed). 

An alternative solution would be to expect the php language server to be pre-installed on the system. This, however, is more hassle for users and there is no "standard" way of installing the php language server since it has no main executable that could be put on the PATH.

**Comment by orucky** [comment]
just a note to the current setup: `composer` checks out JetBrains' `phpstorm-stubs` repo and leaves it in the directory tree together with the `.git` folder (applies also to Gitpod as it has `@theia/php` as a dependency). Then you might have noticed that the universal cleanup command `git clean -fdx` says
```
Skipping repository node_modules/@theia/php/vendor/jetbrains/phpstorm-stubs
```
Issue `git clean -ffdx` to get rid of that, too

**Comment by pwFoo** [comment]
I would use theia as standalone container. So I need a installed php inside of the container because there is no installed php in the host system.
At the moment I use a [code-server](https://github.com/cdr/code-server) based custom image, which just add php and works fine for me. 

Would be great to have a theia php docker image ready to run with all needed dependencies (like php).

**Comment by meysholdt** [comment]
hey @pwFoo, [theia-full-docker](https://github.com/theia-ide/theia-apps/tree/master/theia-full-docker) also includes PHP. Is that what you're looking for?

**Comment by pwFoo** [comment]
Hi @meysholdt,
thank's that working for me!
