### ISSUE TITLE
Update NPM package registry - composer files

### ISSUE THREAD

**Issue by 4oo4** [theia-ide/theia-php-extension#13]
I can see that this was updated in the repo, however attempting to install from the `@theia/php` packages (`next` and `latest`) still fail to include the composer files:

```
theia@6f644cd82a69:~/node_modules/@theia/php$ cat package.json
{
  "name": "@theia/php",
  "keywords": [
    "theia-extension"
  ],
  "version": "0.1.0-next.917d6e56",
  "files": [
    "data",
    "lib",
    "src"
  ],
  "dependencies": {
    "@theia/core": "next",
    "@theia/monaco": "next"
  },
  "devDependencies": {
    "lerna": "2.4.0",
    "rimraf": "latest",
    "typescript": "latest"
  },
  "publishConfig": {
    "access": "public"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn run build",
    "postinstall": "composer install",
    "clean": "rimraf lib",
    "build": "tsc",
    "watch": "tsc -w"
  },
  "theiaExtensions": [
    {
      "frontend": "lib/browser/theia-php-frontend-module",
      "backend": "lib/node/theia-php-backend-module"
    }
  ]
}
```
Can you please update the package to include the latest commits? Looks like this is what solves the issue: https://github.com/theia-ide/theia-php-extension/commit/6a591c46c61dc7675b5ecc923d9c4bf8b36bb1a1

Cheers

**Comment by meysholdt** [comment]
I've re-published `theia-php-extension` to the npm registry. 

`yarn add @theia/php:next` succeeds now for me. 

Let me know if I missed anything.

**Comment by 4oo4** [comment]
@meysholdt  Thank you!
