### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia-php-extension#6]
Also would be nice to add a new docker image to theia-apps: https://github.com/theia-ide/theia-apps

**Comment by designerbase** [comment]
@akosyakov  Hi, i update my dockerfile with your latest dockerfile change and next.pakage.json also, everything fine, but still the php syntax are not highlighted yet. will you please help me out. i am running theia-ide in docker
here i posted my docker change and pakage json 

docker file
-----------------------
#PHP
RUN apt-get -y install php curl php-cli php-mbstring unzip

# https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
# https://linuxconfig.org/how-to-install-php-composer-on-debian-linux
RUN curl -s -o composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php


pakage.json
-----------------------

{
    "private": true,

    "dependencies": {
        "@theia/plugin-ext-vscode": "next",
        "@theia/callhierarchy": "next",
        "@theia/core": "next",
        "@theia/cpp": "next",
        "@theia/docker": "next",
        "@theia/editor": "next",
        "@theia/editorconfig": "next",
        "@theia/editor-preview": "next",
        "@theia/extension-manager": "next",
        "@theia/file-search": "next",
        "@theia/filesystem": "next",
        "@theia/git": "next",
        "@theia/go": "next",
        "@theia/getting-started": "next",
        "@theia/java": "next",
        "@theia/json": "next",
        "@theia/keymaps": "next",
        "@theia/languages": "next",
        "@theia/markers": "next",
        "@theia/merge-conflicts": "next",
        "@theia/messages": "next",
        "@theia/metrics": "next",
        "@theia/mini-browser": "next",
        "@theia/monaco": "next",
        "@theia/navigator": "next",
        "@theia/outline-view": "next",
        "@theia/output": "next",
        "@theia/php": "next",
        "@theia/plantuml": "next",
        "@theia/plugin": "next",
        "@theia/plugin-ext": "next",
        "@theia/plugin-ext-vscode": "next",
        "@theia/preferences": "next",
        "@theia/preview": "next",
        "@theia/process": "next",
        "@theia/python": "next",
        "@theia/ruby": "next",
        "@theia/rust": "next",
        "@theia/search-in-workspace": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/textmate-grammars": "next",
        "@theia/tslint": "next",
        "@theia/typescript": "next",
        "@theia/userstorage": "next",
        "@theia/variable-resolver": "next",
        "@theia/workspace": "next",
        "theia-yang-extension": "next",
        "typescript": "latest"
    },
    "devDependencies": {
        "@theia/cli": "next"
    }
}
